name: 'pr-comment-test-sharing'
description: 'Post a comment on PR with a random Giphy image'
inputs:
  github-token:
    description: 'GitHub Token'
    required: true
  giphy-api-key:
    description: 'Giphy API Key '
    required: true
runs:
  using: 'node20'
  main: 'dist/index.js'

branding:
  icon: 'gift'
  color: 'orange'

